### ISSUE TITLE
Existing guilds are not found during the Discord OAuth callback 

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#1027]
### What happened?

Screensharing with Magenta of Bloom Network, I saw a server error after she clicked "Join Guild" and went through the discord OAuth flow. 

```
Jan 6 02:20:33 PM  ClientError: Uniqueness violation. duplicate key value violates unique constraint "guild_discord_id_key": {"response":{"errors":[{"extensions":{"path":"$.selectionSet.insert_guild_one.args.object","code":"constraint-violation"},"message":"Uniqueness violation. duplicate key value violates unique constraint \"guild_discord_id_key\""}],"status":200},"request":{"query":"mutation CreateGuild($object: guild_insert_input!) {\n  insert_guild_one(object: $object) {\n    guildname\n    id\n  }\n}\n","variables":{"object":{"discord_id":"778283552646627349", [redacted]}}}}    at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/dist/index.js:170:35)    at step (/app/node_modules/graphql-request/dist/index.js:63:23)    at Object.next (/app/node_modules/graphql-request/dist/index.js:44:53)    at fulfilled (/app/node_modules/graphql-request/dist/index.js:35:58)    at runMicrotasks (<anonymous>)    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
Jan 6 02:20:33 PM    response: { errors: [ [Object] ], status: 200 },
Jan 6 02:20:33 PM    request: {
Jan 6 02:20:33 PM      query: 'mutation CreateGuild($object: guild_insert_input!) {\n' +
Jan 6 02:20:33 PM        '  insert_guild_one(object: $object) {\n' +
Jan 6 02:20:33 PM        '    guildname\n' +
Jan 6 02:20:33 PM        '    id\n' +
Jan 6 02:20:33 PM        '  }\n' +
Jan 6 02:20:33 PM        '}\n',
Jan 6 02:20:33 PM      variables: { object: [Object] }
Jan 6 02:20:33 PM    }
Jan 6 02:20:33 PM  }
Jan 6 02:20:43 PM  400: Bad Request
Jan 6 02:20:43 PM  Error
Jan 6 02:20:43 PM      at /app/packages/backend/dist/handlers/actions/guild/discord/oauthHandler.js:26:19
Jan 6 02:20:43 PM      at Generator.next (<anonymous>)
Jan 6 02:20:43 PM      at fulfilled (/app/packages/backend/dist/handlers/actions/guild/discord/oauthHandler.js:5:58)
Jan 6 02:20:43 PM      at runMicrotasks (<anonymous>)
Jan 6 02:20:43 PM      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Existing guilds should be found and updated by their Discord ID.

### What did you expect to happen?

Guild should have been found

**Comment by alalonde** [comment]
Also, during the call we agreed to make the help text for the role selection fields clearer, as well as not showing the "@everyone" role in the guild membership component.
