### ISSUE TITLE
Pull request test instance build failing on `/players`

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1467]
### What happened?

During the build of the frontend Docker image, the process is failing with the error:

```
@metafam/web: info  - Generating static pages (0/304)
@metafam/web: GraphQL Retry ***
@metafam/web:   error: [CombinedError: [GraphQL] Remote server response is not valid JSON: Failed reading: not a valid json value] ***
@metafam/web:     graphQLErrors: [ [GraphQLError] ],
@metafam/web:     networkError: undefined,
@metafam/web:     response: Response ***
@metafam/web:       size: 0,
@metafam/web:       timeout: 0,
@metafam/web:       [Symbol(Body internals)]: [Object],
@metafam/web:       [Symbol(Response internals)]: [Object]
@metafam/web:     ***
@metafam/web:   ***
@metafam/web: ***
@metafam/web: Error occurred prerendering page "/players". Read more: https://nextjs.org/docs/messages/prerender-error
@metafam/web: Error: getPlayers Error: [GraphQL] Remote server response is not valid JSON: Failed reading: not a valid json value
@metafam/web:     at getStaticProps (/usr/src/app/packages/web/.next/server/pages/players.js:1444:15)
@metafam/web:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
@metafam/web:     at async renderToHTML (/usr/src/app/node_modules/next/dist/server/render.js:386:20)
@metafam/web:     at async /usr/src/app/node_modules/next/dist/export/worker.js:304:36
@metafam/web:     at async Span.traceAsyncFn (/usr/src/app/node_modules/next/dist/trace/trace.js:79:20)
```

### What did you expect to happen?

The frontend to build correctly.

### How can we reproduce the problem (as minimally as possible)?

Push changes to a pull request.

### Is there anything else we need to know?

Note that the returned size is 0. This means that the error is likely because Hasura is not fully started, more than likely in its connection to the backend.

**Comment by dysbulic** [comment]
I'm uncertain about the theory that Hasura hasn't started completely yet because this step is after the seeding step which is writing the same basic data & succeeds.

In any case, adding `error.response?.size === 0` causes the request to retry. One the first retry it fails again with "`Invalid response from authorization hook`", then it succeeds.
